FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie

# python-dbus for dbus communication
# python-flash for example server

RUN apt-get update && apt-get install -y \
      python-dbus \
      python-flask \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app/
RUN git clone \
  git@github.com:resin-io-playground/resin-avahi-dbus.git \
  /usr/src/app/

CMD ["/bin/bash", "/usr/src/app/start.sh"]
